# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84c08ef9fc39a3cc8dbc821a70e2ae1cbf116b86c78f3b2b070c81a52d12a728c5f74460f43961f110d2a018f074b8ba07fa1d4c888002ff60d0081059a7654a

test:
  secret_key_base: b33fe1a878fb7449f9f5790e9a599a4315faa8e3ea6711abba78cfb4dd68b99cf9f6b15aa5f2d6ee6b4867e92dcccecf18f8c074d088f2ded3f233903daab1c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
